pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'NeoForged'
            url = 'https://maven.neoforged.net/releases'
        }
        maven {
            name = 'Forge'
            url = 'https://maven.minecraftforge.net/'
        }
        maven {
            name = 'Wagyourtail'
            url = 'https://maven.wagyourtail.xyz/releases'
        }
        maven {
            name = 'Wagyourtail snapshots'
            url = 'https://maven.wagyourtail.xyz/snapshots'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'LegacyParkourCompat'

includeBuild 'tas-client'
include 'parkourgym-server'
