modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="legacyparkourrecording"
version="${version}"
displayName="Legacy Parkour Recording"
authors="JustAlittleWolf"
description="Records and plays back simulation movement inputs for parkour compatibility testing."
side="CLIENT"
