name: PhysicsTest
version: '${version}'
main: me.wolfii.legacyparkourcompat.physicstest.PhysicsTestPlugin
description: Physics testing helper for Legacy Parkour Compat
api-version: '1.21'
folia-supported: true
authors:
  - JustAlittleWolf
dependencies:
  server:
    polarpaper:
      load: BEFORE
      required: true
      join-classpath: true
permissions:
  physicstest.save:
    description: Save the physics testing world as Polar
    default: true
